"""empty message

Revision ID: 42d99be49033
Revises:
Create Date: 2021-08-20 16:30:28.200473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42d99be49033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PlayerID', sa.String(length=100), nullable=False),
    sa.Column('GameID', sa.Integer(), nullable=True),
    sa.Column('Employment', sa.String(length=50), nullable=False),
    sa.Column('Education', sa.String(length=50), nullable=False),
    sa.Column('Wealth', sa.String(length=50), nullable=False),
    sa.Column('Wage', sa.String(length=50), nullable=False),
    sa.Column('Condition', sa.Integer(), nullable=False),
    sa.Column('FirstGame', sa.Integer(), nullable=False),
    sa.Column('Bankrupt', sa.Integer(), nullable=False),
    sa.Column('GameData', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('GameID'),
    sa.UniqueConstraint('PlayerID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
